environment:
  matrix:
    - nodejs_version: "8"

platform:
  - x64
  - x86

build: off

cache:
  - node_modules -> package.json # local npm modules
  - '%APPDATA%\npm-cache'  # npm cache

install:
  - ps: Install-Product node $env:nodejs_version $env:platform
  - npm install -g npm@5.3
  - npm install

test_script:
  - node --version
  - npm --version
  - npm run build:desktop
  - npm run test:coverage
