# Node.js
# Build a general Node.js project with npm.
# Add steps that analyze code, save build artifacts, deploy, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/javascript

pool:
  vmImage: "Ubuntu 16.04"

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: "10.x"
    displayName: "Install Node.js"

  - script: |
      pip3 install wheel
      pip3 install setuptools
      pip3 install jupyter
      pip3 install ipykernel 
      python3 -m ipykernel install --user
    displayName: "Install Jupyter"

  - script: |
      yarn
      yarn install --verbose
      npx jest --silent
    displayName: "yarn install and test"

  - task: PublishTestResults@2
    displayName: "Publish Test Results"
    inputs:
      testResultsFiles: "**junit*.xml"
      testRunTitle: TestRun ${{ parameters.name }} $(node_version)
