environment:
    matrix:
        - PYTHON: "C:\\Python27"
        - PYTHON: "C:\\Python35"
        - PYTHON: "C:\\Python27-x64"
        - PYTHON: "C:\\Python35-x64"
        - nodejs_version: "5"

install:
    - ps: Install-Product node $env:nodejs_version
    - "SET PATH=%PYTHON%;%PYTHON%\\Scripts;%PATH%"
    - npm install

before_test:
    - "%PYTHON%\\python.exe -m pip install jupyter"

test_script:
    - node --version
    - npm --version
    - npm test

build: off
