# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2
jobs:
  build:
    docker:
      - image: circleci/python:3.7.2-node

    working_directory: ~/nteract

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
            - yarn-packages-{{ checksum "yarn.lock" }}
            # fallback to using the latest cache if no exact match is found
            - yarn-packages-

      - run: pip install --user setuptools
      - run: pip install --user jupyter
      - run: yarn

      - save_cache:
          paths:
            - ~/.cache/yarn
          key: yarn-packages-{{ checksum "yarn.lock" }}

      # run tests!
      - run: yarn run test:lint
      - run: yarn run build:packages:ci
      - run: yarn run test --maxWorkers 1

      - run:
          name: Check Types For Applications
          command: |
            echo '**** Reporting on types for Jupyter Extension ****'
            yarn report:jext
            echo '**** Reporting on types for Desktop ****'
            yarn report:desktop
            echo '**** Reporting on types for Play ****'
            yarn report:play
            echo '**** Application type reporting finished ****'

      - run: yarn run test:flow

      - run:
          name: Build Docs
          command: yarn run docs:build

      - store_artifacts:
          path: styleguide
          destination: styleguide

      - run:
          name: Build Commuter
          command: npx lerna run build --scope @nteract/commuter
          no_output_timeout: 20m
      - run:
          name: Build Play
          command: npx lerna run build --scope @nteract/play
          no_output_timeout: 20m
      - run:
          name: Build Jupyter Extension
          command: npx lerna run build:asap --scope nteract-on-jupyter
          no_output_timeout: 30m
