language: node_js

sudo: false

node_js: 
  - "5.4"

addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
      - gcc-4.8
      - uuid-dev
      - wget

cache:
  apt: true
  directories:
    - node_modules

